---
title: "Checkpoint 2 - Problema 2"
author: "João Victor Barroso Mafra"
date: "26 de julho de 2016"
output: html_document
---

```{r}
library(dplyr, warn.conflicts = FALSE)
library(ggplot2)
library(knitr)
theme_set(theme_bw())
```

```{r}
ler_gastos <- function(arquivo = "dados/ano-atual.csv"){
  
  
  #' L? um csv criado a partir dos dados de gastos dos deputados da 
  #' C?mara e seta os tipos de colunas mais convenientemente. 
  #' Vers?o sem readr, para m?quinas onde n?o ? poss?vel instalar esse pacote. 
  #' ? um pouco mais lenta que a com readr.
  require("dplyr", warn.conflicts = FALSE)
  
  gastos = read.csv(arquivo, stringsAsFactors = FALSE, encoding='UTF-8')
  gastos = gastos %>% 
    mutate_each(funs(as.factor), sgPartido, sgUF, txNomeParlamentar, indTipoDocumento)
  return(gastos)
}

gastos <- ler_gastos()


gastos <- gastos %>% select (1, 5, 6, 15, 23)

names(gastos) <- c("Partido", "Nome", "UF", "Tipo", "Valor")

gastos_pb <- gastos %>% filter (UF == "PB")
```



```{r fig.width=10, fig.height=5}
agrupa_atividade = gastos_pb %>% filter(Tipo == "DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.") %>% group_by(Nome, Partido) %>% summarise(Divulgacao = sum(Valor))


agrupa_nome = gastos_pb %>% 
  group_by(Nome, Partido) %>% 
  summarise(total_gasto = sum(Valor))

ggplot(agrupa_nome, aes(x = reorder(Nome, total_gasto),  
                        y = total_gasto,  
                        fill = Partido)) + 
  geom_bar(stat = "summary", fun.y = "mean") + 
  
  scale_fill_manual(values = c("chartreuse4", "azure4", "cadetblue3", "darkgoldenrod3", "darkorchid", "darkred", "deeppink2", "orange", "red", "lawngreen", "burlywood1")) +
  
  geom_text(aes(label = sprintf("R$ %i",as.integer(total_gasto))), hjust=1, vjust=1, fontface = "bold", colour = "white") +
  xlab("Nome do deputado") + 
  ylab("Total Gasto") + coord_flip() + 
  geom_point(data = agrupa_atividade, aes(x = Nome, y = Divulgacao, size = Divulgacao), colour = "black", show.legend = TRUE, shape = 21) +
  
  geom_point(data = gastos_pb, aes(x = Nome, y = Valor), colour = "black", show.legend = FALSE)

```
